# Generated by Django 4.1.7 on 2023-10-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField()),
                ('q_name', models.CharField(max_length=100)),
                ('q_desc', models.TextField()),
                ('q_examples', models.TextField()),
                ('q_code', models.TextField()),
                ('q_soln', models.TextField()),
            ],
        ),
    ]
