# Generated by Django 4.1.7 on 2023-10-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_questions_q_soln'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='q_soln',
            field=models.TextField(blank=True),
        ),
    ]
